AM_CPPFLAGS = -I$(top_srcdir)/$(ycc_headerdir) -Wall -Werror

install-header:
	$(MKDIR_P) "$(DESTDIR)$(includedir)" || exit $?
	cp -av $(top_srcdir)/$(ycc_headerdir)/ycc "$(DESTDIR)$(includedir)" \
		|| exit $?
